In [1]:
import pandas as pd
soil_df=pd.read_excel('/Users/nickstatz/Desktop/CornYield/SoilMerged.xlsx')
rest_df=pd.read_excel('/Users/nickstatz/Desktop/CornYield/Dropped2010-2020.xlsx')

In [4]:
merged=soil_df.merge(rest_df,left_on=['Year','GEOID'],right_on=['Year','GEOID'])

In [5]:
merged

,Year,GEOID,AWCmean,CECMean,OCDmean,x,Yield,EVI Average,NDVI Average,GCI Average,NDWI Average
0,2010,5063,14.546161,19.094277,256.464574,12,130.0,0.351410,0.516680,2.728479,-0.076958
1,2010,5067,14.754726,19.042175,222.711286,13,150.0,0.340833,0.486366,2.523245,-0.055194
2,2010,5121,14.690079,19.121303,244.529345,30,130.0,0.348775,0.494331,2.662388,-0.051745
3,2010,5093,14.101840,20.899450,230.774988,23,166.0,0.333715,0.463979,2.525566,-0.065515
4,2010,5095,14.654235,20.037244,246.662318,24,143.0,0.367096,0.518080,2.834970,-0.051252
...,...,...,...,...,...,...,...,...,...,...,...
8864,2020,55117,16.245889,27.581528,404.975714,881,162.2,0.372817,0.553292,3.119724,0.002781
8865,2020,55139,15.951065,29.215066,407.824897,892,150.8,0.360200,0.540196,3.171092,-0.005588
8866,2020,55029,17.316416,24.363932,464.062694,843,125.3,0.372681,0.565959,3.166413,0.013161
8867,2020,55081,17.028700,25.753994,402.307727,865,155.1,0.410045,0.600312,3.785952,-0.000155
8868,2020,55079,13.831828,30.624655,397.769795,864,191.7,0.343558,0.528390,2.684892,-0.026583

In [1]:
import pandas as pd
temps=pd.read_excel('/Users/nickstatz/Desktop/CornYield/TempMeans.xlsx')
ppt=pd.read_excel('/Users/nickstatz/Desktop/CornYield/PPTMean.xlsx')
merged_df=pd.read_excel('/Users/nickstatz/Desktop/CornYield/FinalMerge.xlsx')

In [2]:
temps.head()

   GEOID  Year    MaxMean   MeanMean    MinMean
0   1001  2010  28.581350  22.029962  15.479591
1   1005  2010  28.710217  21.650632  14.592038
2   1023  2010  29.082774  21.698643  14.315453
3   1035  2010  28.498159  21.802054  15.106955
4   1051  2010  28.707961  21.832787  14.958567

In [3]:
ppt.head()

   GEOID  Year   PPTmean
0   1001  2010  2.974820
1   1005  2010  2.619083
2   1023  2010  3.444861
3   1035  2010  3.096925
4   1051  2010  2.827906

In [4]:
merged_df.head()

,Unnamed: 0,Year,Yield,GEOID,AWCmean,CECMean,OCDmean,EVI Average,NDVI Average,GCI Average,NDWI Average
0,0,2010,130.0,5063,14.546161,19.094277,256.464574,0.351410,0.516680,2.728479,-0.076958
1,1,2010,150.0,5067,14.754726,19.042175,222.711286,0.340833,0.486366,2.523245,-0.055194
2,2,2010,130.0,5121,14.690079,19.121303,244.529345,0.348775,0.494331,2.662388,-0.051745
3,3,2010,166.0,5093,14.101840,20.899450,230.774988,0.333715,0.463979,2.525566,-0.065515
4,4,2010,143.0,5095,14.654235,20.037244,246.662318,0.367096,0.518080,2.834970,-0.051252

In [5]:
merge1=merged_df.merge(ppt,left_on=['Year','GEOID'],right_on=['Year','GEOID'])

In [7]:
merge2=merge1.merge(temps,left_on=['Year','GEOID'],right_on=['Year','GEOID'])

In [8]:
merge2

,Unnamed: 0,Year,Yield,GEOID,AWCmean,CECMean,OCDmean,EVI Average,NDVI Average,GCI Average,NDWI Average,PPTmean,MaxMean,MeanMean,MinMean
0,0,2010,130.0,5063,14.546161,19.094277,256.464574,0.351410,0.516680,2.728479,-0.076958,3.035817,26.840109,20.497388,14.155641
1,1,2010,150.0,5067,14.754726,19.042175,222.711286,0.340833,0.486366,2.523245,-0.055194,3.003970,26.779713,20.784387,14.790069
2,2,2010,130.0,5121,14.690079,19.121303,244.529345,0.348775,0.494331,2.662388,-0.051745,2.993533,26.222520,20.029503,13.837489
3,3,2010,166.0,5093,14.101840,20.899450,230.774988,0.333715,0.463979,2.525566,-0.065515,2.860128,27.062886,21.059436,15.056977
4,4,2010,143.0,5095,14.654235,20.037244,246.662318,0.367096,0.518080,2.834970,-0.051252,2.693002,27.435930,21.460487,15.486050
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8864,8864,2020,162.2,55117,16.245889,27.581528,404.975714,0.372817,0.553292,3.119724,0.002781,3.326646,17.271363,12.294380,7.317488
8865,8865,2020,150.8,55139,15.951065,29.215066,407.824897,0.360200,0.540196,3.171092,-0.005588,3.081543,17.825263,12.678469,7.531764
8866,8866,2020,125.3,55029,17.316416,24.363932,464.062694,0.372681,0.565959,3.166413,0.013161,3.263782,15.829407,11.318877,6.808435
8867,8867,2020,155.1,55081,17.028700,25.753994,402.307727,0.410045,0.600312,3.785952,-0.000155,3.199670,17.723286,11.884950,6.046695
8868,8868,2020,191.7,55079,13.831828,30.624655,397.769795,0.343558,0.528390,2.684892,-0.026583,3.338462,18.399728,12.818468,7.237298

In [9]:
merge2.to_excel('MissingVPD.xlsx')